#cleaning inputs should all be converted to lower case before being used with this dict
clean_drug_names = {
    "3,4 methylenedioxyamphetamine (mda)":"MDA",
    "n-ethyl-3,4-methylenedioxyamphetamine (mdea)":"MDEA",
    "n-methyl-3,4-methylenedioxyamphetamine (mdma)":"MDMA",
    "adderall xr 10mg cap":"Adderall",
    "adderall xr 30mg cap":"Adderall",
    "adderall xr 5mg cap":"Adderall",
    "amphetamine":"Amphetamine",
    "benzedrine 10mg":"Benzedrine",
    "benzylpiperazine (bzp)":"Benzylpiperazine",
    "dexedrine 5mg":"Dexedrine",
    "dexedrine spansule 10mg cap":"Dexedrine",
    "dextroamphetamine":"Dextroamphetamine",
    "diethylpropion":"Diethylpropion",
    "ionamin 15":"Ionamin",
    "mephedrone":"Mephedrone",
    "methylenedioxypyrovalerone (mdpv)":"MDPV",
    "vyvanse 10mg cap":"Vyvanse",
    "vyvanse 30mg cap":"Vyvanse",
    "vyvanse 40mg cap":"Vyvanse",
    "ephedrine":"Ephedrine",
    "khat (catha edulis)":"Khat",
    "desoxyn 5mg":"Desoxyn",
    "methamphetamine":"Methamphetamine",
    "biphentin 10mg/cap":"Methylphenidate",
    "biphentin 20mg/cap":"Methylphenidate",
    "concerta 18mg tab":"Methylphenidate",
    "concerta 36mg tab":"Methylphenidate",
    "concerta 54mg tab":"Methylphenidate",
    "methylphenidate":"Methylphenidate",
    "ritalin 10mg":"Methylphenidate",
    "ritalin 20mg":"Methylphenidate",
    "ritalin sr tab":"Methylphenidate",
    "4-bromo-2,5-dimethoxybenzeneethanamine":"4-bromo-2,5-dimethoxybenzeneethanamine",
    "3-trifluoromethylphenylpiperazine (tfmpp)":"TFMPP",
    "cannabis (gplm)":"Cannabis",
    "cannabis":"Cannabis",
    "cbd cannabidiol":"CBD cannabidiol",
    "edible cannabis":"Edible cannabis",
    "edible hash":"Hash",
    "hash":"Hash",
    "hash oil":"Hash oil",
    "cesamet 0.25mg":"Synthetic cannabinoid",
    "hemp":"Hemp",
    "non-edible cannabis product":"Non-edible cannabis",
    "nabilone":"Synthetic cannabinoid",
    "synthetic cannabinoids":"Synthetic cannabinoid",
    "edible thc":"Edible cannabis",
    "thc tetrahydrocannabinol":"THC tetrahydrocannabinol",
    "cocaine":"Cocaine",
    "lysergic acid diethylamide (lsd)":"LSD",
    "mescaline":"Mescaline",
    "n,n-dimethyltryptamine(dmt)":"DMT",
    "phencyclidine (pcp)":"PCP",
    "salvia":"Salvia",
    "psilocybin":"Psilocybin",
    "buprenorphine":"Buprenorphine",
    "codeine":"Codeine",
    "codeine 15mg":"Codeine",
    "codeine 30mg":"Codeine",
    "codeine 8mg":"Codeine",
    "codeine contin 50mg":"Codeine",
    "codeine syrup  5mg/ml":"Codeine",
    "ratio-codeine 30mg tab":"Codeine",
    "ratio-lenoltec 1 tab":"Lenoltec",
    "ratio-lenoltec 3 tab":"Lenoltec",
    "diacetylmorphine":"Diacetylmorphine",
    "fentanyl":"Fentanyl",
    "fentanyl 100 mcg patch":"Fentanyl",
    "fentanyl 25 mcg patch":"Fentanyl",
    "fentanyl 50 mcg patch":"Fentanyl",
    "novahistex dh":"Novahistex",
    "hydromorphine":"Dilaudid",
    "dilaudid 1 mg":"Dilaudid",
    "dilaudid 1mg/ml":"Dilaudid",
    "dilaudid 2 mg":"Dilaudid",
    "dilaudid 4 mg":"Dilaudid",
    "dilaudid 8 mg":"Dilaudid",
    "hydromorph contin 12mg cap":"Dilaudid",
    "hydromorph contin 18mg cap":"Dilaudid",
    "hydromorph contin 24mg cap":"Dilaudid",
    "hydromorph contin 30mg cap":"Dilaudid",
    "hydromorph contin 3mg cap":"Dilaudid",
    "hydromorph contin 6mg cap":"Dilaudid",
    "hydromorph contin 9 mg cap":"Dilaudid",
    "hydromorphone":"Dilaudid",
    "hydromorphone 15mg":"Dilaudid",
    "hydromorphone 1mg":"Dilaudid",
    "hydromorphone 1mg/ml":"Dilaudid",
    "hydromorphone 2mg":"Dilaudid",
    "hydromorphone 3mg sup":"Dilaudid",
    "hydromorphone 4mg":"Dilaudid",
    "hydromorphone 8mg":"Dilaudid",
    "hydromorphone hp 30mg/ml":"Dilaudid",
    "pms hydromorphone 1":"Dilaudid",
    "morphine 1mg/ml edp usp inj":"Morphine",
    "morphine 1mg/ml lp":"Morphine",
    "morphine 30mg cap":"Morphine",
    "morphine sr 100 mg tab":"Morphine",
    "morphine sul 10mg tab":"Morphine",
    "morphine sul 15mg tab":"Morphine",
    "morphine sul 30mg tab":"Morphine",
    "morphine sul 50mg/ml inj":"Morphine",
    "morphine sul 5mg/ml usp inj":"Morphine",
    "morphine sul inj sdz 10mg/ml":"Morphine",
    "morphine sulfate":"Morphine",
    "teva-morphine sr 15 tab":"Morphine",
    "1-phenethyl-4-piperidone":"1-phenethyl-4-piperidone",
    "methadone":"Methadone",
    "opium":"Opium",
    "acetaminophen 325mg & codeine":"Codeine",
    "atasol 8":"Codeine",
    "carfentanil":"Carfentanil",
    "demerol 10% 100mg/ml liq/inj":"Pethidine",
    "demerol 50mg":"Pethidine",
    "doda (morphine/codeine blend)":"Morphine/codeine blend",
    "emtec 60mg":"Codeine",
    "endocet":"Oxycodone",
    "ms contin 60mg tab sr":"Morphine",
    "mylan-buprenorphine/naloxone":"Mylan-buprenorphine/naloxone",
    "nucynta er 100mg":"Tapentadol",
    "nucynta ir 50mg":"Tapentadol",
    "oxymorphone":"Oxymorphone",
    "ratio-tecnal c 1/2 cap":"Ratio-tecnal",
    "ratio-tecnal tab":"Ratio-tecnal",
    "synthetic opioids":"Synthetic opioids",
    "talwin 50mg":"Pentazocine",
    "targin 2.5/5 mg":"Targin",
    "tussionex":"Hydrocodone",
    "apo-oxycodone cr 60 mg/tab":"Apo-oxycodone",
    "apo-oxycodone cr 80 mg/tab":"Apo-oxycodone",
    "oxycodone":"Oxycodone",
    "oxycodone 10mg":"Oxycodone",
    "oxycodone 20mg":"Oxycodone",
    "oxycodone 40mg":"Oxycodone",
    "oxycodone 5/mg tab":"Oxycodone",
    "oxycontin 10mg srt":"Oxycontin",
    "oxycontin 20mg srt":"Oxycontin",
    "oxycontin 5mg srt":"Oxycontin",
    "oxycontin 80mg srt":"Oxycontin",
    "oxyneo 10mg/tab":"Oxyneo",
    "oxyneo 20mg/tab":"Oxyneo",
    "oxyneo 30mg/tab":"Oxyneo",
    "oxyneo 40mg/tab":"Oxyneo",
    "oxyneo 80mg/tab":"Oxyneo",
    "percocet":"Percocet",
    "percodan":"Percodan",
    "ratio-oxycocet 5mg/tab":"Oxycocet",
    "lomotil":"Diphenoxylate",
    "m-eslon 100mg":"M-eslon",
    "m-eslon 10mg":"M-eslon",
    "suboxone 2mg":"Suboxone",
    "suboxone 8mg":"Suboxone",
    "supeudol 10 mg":"Oxycodone",
    "elavil 10mg syrup":"Elavil",
    "tylenol 1":"N/A",
    "tylenol 2":"N/A",
    "tylenol 3":"N/A",
    "tylenol 4":"N/A",
    "unknown":"N/A",
    "mogadon 5mg tab":"Mogadon",
    "gravergol 1mg cap":"Gravergol",
    "hycodan":"Hycodan",
    "boldenone":"Boldenone",
    "deca durabolin 25mg/ml inj":"Durabolin",
    "drostanolone":"Drostanolone",
    "equipoise 50mg/ml inj":"Equipoise",
    "masteron":"Masteron",
    "methandrostenolone":"Methandrostanolone",
    "nandrolone":"Nandrolone",
    "oxandrolone":"Oxandrolone",
    "oxymetholone":"Oxymetholone",
    "parabolan":"Parabolan",
    "primobolan":"Primobolan",
    "steroids":"Steroids",
    "sustanon 250":"Sustanon",
    "testosterone":"Testosterone",
    "trenbolone":"Trenbolone",
    "midazolam":"Midazolam",
    "gamma hydroxybutyrate(ghb)":"Ghb",
    "ketamine":"Ketamine",
    "alprazolam":"Alprazolam",
    "alprazolam 0.5mg":"Alprazolam",
    "amytal 15mg":"Amytal",
    "apodiazepam 2mg":"Apodiazepam",
    "apolorazepam 0.5mg":"Apolorazepam",
    "apotemazepam 30mg":"Apotemazepam",
    "ativan 0.5mg":"Ativan",
    "benzodiazepines":"Benzodiazepines",
    "bromazepam":"Bromazepam",
    "clonapam 0.5mg":"Clonapam",
    "clonapam 1mg":"Clonapam",
    "clonazepam":"Clonazepam",
    "clonazepam 0.5mg":"Clonazepam",
    "clonazepam 1mg":"Clonazepam",
    "clonazepam 2mg":"Clonazepam",
    "cyclobarbital":"Cyclobarbital",
    "diazepam":"Diazepam",
    "diazepam 10mg":"Diazepam",
    "diazepam 5mg":"Diazepam",
    "etizolam":"Etizolam",
    "fiorinal":"Fiorinal",
    "flubromazolam":"Flubromazolam",
    "lendormin":"Lendormin",
    "librax 5mg":"Librax",
    "librium 10mg":"Librium",
    "lorazepam":"Lorazepam",
    "lorazepam 0.5 mg tab":"Lorazepam",
    "lorazepam 1 mg tab":"Lorazepam",
    "lorazepam 2 mg tab":"Lorazepam",
    "mandrax":"Mandrax",
    "nitrazadon 10mg":"Nitrazadon",
    "nitrazepam":"Nitrazepam",
    "novodipam 2mg":"Novodipam",
    "oxazepam":"Oxazepam",
    "oxazepam 10 tab":"Oxazepam",
    "oxazepam 15 tab":"Oxazepam",
    "oxazepam 30 tab":"Oxazepam",
    "phenobarbital":"Phenobarbital",
    "prazepam":"Prazepam",
    "seconal sod 50mg":"Seconal",
    "temazepam":"Temazepam",
    "temazepam 15mg":"Temazepam",
    "temazepam 30mg":"Temazepam",
    "trianal tab":"Trianal ",
    "triazolam":"Triazolam",
    "valium 10mg":"Valium",
    "valium 2mg":"Valium",
    "xanax 0.25mg":"Xanax",
    "xanax 0.5mg":"Xanax",
    "xanax 1mg":"Xanax",
    "xanax ts 2mg":"Xanax",
    "clobazam":"Clobazam",
    "trazodone hydrochloride":"Trazodone",
    "ambien cr":"Ambien",
    "zolpidem":"Zolpidem"
    }

drug_classifications = (
    {"drug_name":"MDA","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Methamphetamine","drug_cat_3":""},
    {"drug_name":"MDEA","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Methamphetamine","drug_cat_3":""},
    {"drug_name":"MDMA","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Methamphetamine","drug_cat_3":""},
    {"drug_name":"Adderall","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Amphetamine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Benzedrine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Benzylpiperazine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Dexedrine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Dextroamphetamine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Diethylpropion","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Ionamin","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Diverted/counterfeit prescription amphetamine-type stimulants (specify)","drug_cat_3":"Ionamin"},
    {"drug_name":"Mephedrone","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"MDPV","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Other stimulants (specify)","drug_cat_3":"MDPV"},
    {"drug_name":"Vyvanse","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Amphetamine","drug_cat_3":""},
    {"drug_name":"Ephedrine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Other stimulants (specify)","drug_cat_3":"Ephedrine"},
    {"drug_name":"Khat","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Other stimulants (specify)","drug_cat_3":"Khat"},
    {"drug_name":"Desoxyn","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Methamphetamine","drug_cat_3":""},
    {"drug_name":"Methamphetamine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Methamphetamine","drug_cat_3":""},
    {"drug_name":"Methylphenidate","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Diverted/counterfeit prescription amphetamine-type stimulants (specify)","drug_cat_3":"Methylphenidate"},
    {"drug_name":"4-bromo-2,5-dimethoxybenzeneethanamine","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Other stimulants (specify)","drug_cat_3":"4-bromo-2,5-dimethoxybenzeneethanamine"},
    {"drug_name":"TFMPP","drug_cat_1":"Amphetamine-type stimulants","drug_cat_2":"Ecstasy-type substances","drug_cat_3":""},
    {"drug_name":"Cannabis","drug_cat_1":"Cannabis","drug_cat_2":"Marijuana (herb)","drug_cat_3":""},
    {"drug_name":"CBD cannabidiol","drug_cat_1":"Cannabis","drug_cat_2":"Oil","drug_cat_3":""},
    {"drug_name":"Edible cannabis","drug_cat_1":"Cannabis","drug_cat_2":"Other types of cannabis (specify)","drug_cat_3":"Edible cannabis"},
    {"drug_name":"Hash","drug_cat_1":"Cannabis","drug_cat_2":"HASH","drug_cat_3":""},
    {"drug_name":"Hash oil","drug_cat_1":"Cannabis","drug_cat_2":"Oil","drug_cat_3":""},
    {"drug_name":"Synthetic cannabinoid","drug_cat_1":"Cannabis","drug_cat_2":"Other types of cannabis (specify)","drug_cat_3":"Synthetic cannabinoid"},
    {"drug_name":"Hemp","drug_cat_1":"Cannabis","drug_cat_2":"Other types of cannabis (specify)","drug_cat_3":"Hemp"},
    {"drug_name":"Non-edible cannabis","drug_cat_1":"Cannabis","drug_cat_2":"Other types of cannabis (specify)","drug_cat_3":"Non-edible cannabis"},
    {"drug_name":"THC tetrahydrocannabinol","drug_cat_1":"Cannabis","drug_cat_2":"oil","drug_cat_3":""},
    {"drug_name":"Cocaine","drug_cat_1":"Cocaine","drug_cat_2":"Salt (cocaine HCl, powder cocaine)","drug_cat_3":""},
    {"drug_name":"LSD","drug_cat_1":"Hallucinogens","drug_cat_2":"LSD","drug_cat_3":""},
    {"drug_name":"Mescaline","drug_cat_1":"Hallucinogens","drug_cat_2":"mescaline","drug_cat_3":""},
    {"drug_name":"DMT","drug_cat_1":"Hallucinogens","drug_cat_2":"Other hallucinogens (specify)","drug_cat_3":"DMT"},
    {"drug_name":"PCP","drug_cat_1":"Hallucinogens","drug_cat_2":"Other hallucinogens (specify)","drug_cat_3":"PCP"},
    {"drug_name":"Salvia","drug_cat_1":"Hallucinogens","drug_cat_2":"Other hallucinogens (specify)","drug_cat_3":"Salvia"},
    {"drug_name":"Psilocybin","drug_cat_1":"Hallucinogens","drug_cat_2":"Other hallucinogens (specify)","drug_cat_3":"Psilocybin"},
    {"drug_name":"Buprenorphine","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Buprenorphine"},
    {"drug_name":"Codeine","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Codeine"},
    {"drug_name":"Lenoltec","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Lenoltec"},
    {"drug_name":"Diacetylmorphine","drug_cat_1":"Illicit opioids","drug_cat_2":"Heroin","drug_cat_3":""},
    {"drug_name":"Fentanyl","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Fentanyl"},
    {"drug_name":"Novahistex","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Novahistex"},
    {"drug_name":"Dilaudid","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Dilaudid"},
    {"drug_name":"Morphine","drug_cat_1":"Illicit opioids","drug_cat_2":"Illicit Morphine","drug_cat_3":""},
    {"drug_name":"1-phenethyl-4-piperidone","drug_cat_1":"Illicit opioids","drug_cat_2":"Other illicit opioids (specify)","drug_cat_3":"1-phenethyl-4-piperidone"},
    {"drug_name":"Methadone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Methadone"},
    {"drug_name":"Opium","drug_cat_1":"Illicit opioids","drug_cat_2":"Opium (raw and prepared)","drug_cat_3":""},
    {"drug_name":"Carfentanil","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Carfentanil"},
    {"drug_name":"Pethidine","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Pethidine"},
    {"drug_name":"Morphine/codeine blend","drug_cat_1":"Illicit opioids","drug_cat_2":"Other illiict opioids (specify)","drug_cat_3":"Morphine/codeine blend"},
    {"drug_name":"Oxycodone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Oxycodone"},
    {"drug_name":"Mylan-buprenorphine/naloxone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Mylan-buprenorphine/naloxone"},
    {"drug_name":"Tapentadol","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Tapentadol"},
    {"drug_name":"Oxymorphone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Oxymorphone"},
    {"drug_name":"Ratio-tecnal","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Synthetic opioids","drug_cat_1":"Illicit opioids","drug_cat_2":"Other illiict opioids (specify)","drug_cat_3":"Synthetic opioids"},
    {"drug_name":"Pentazocine","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Pentazocine"},
    {"drug_name":"Targin","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Targin"},
    {"drug_name":"Hydrocodone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Hydrocodone"},
    {"drug_name":"Apo-oxycodone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Apo-oxycodone"},
    {"drug_name":"Oxycontin","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Oxycontin"},
    {"drug_name":"Oxyneo","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Oxyneo"},
    {"drug_name":"Percocet","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Percocet"},
    {"drug_name":"Percodan","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Percodan"},
    {"drug_name":"Oxycocet","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Oxycocet"},
    {"drug_name":"Diphenoxylate","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Diphenoxylate"},
    {"drug_name":"M-eslon","drug_cat_1":"Illicit opioids","drug_cat_2":"Illicit Morphine","drug_cat_3":""},
    {"drug_name":"Suboxone","drug_cat_1":"Illicit opioids","drug_cat_2":"Diverted/counterfeit pharmaceutical drugs containing opioids under international control (specify)","drug_cat_3":"Suboxone"},
    {"drug_name":"Elavil","drug_cat_1":"N/A","drug_cat_2":"N/A","drug_cat_3":""},
    {"drug_name":"N/A","drug_cat_1":"N/A","drug_cat_2":"N/A","drug_cat_3":""},
    {"drug_name":"Mogadon","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Gravergol","drug_cat_1":"Other(specify)","drug_cat_2":"Other(specify)","drug_cat_3":"Gravergol"},
    {"drug_name":"Hycodan","drug_cat_1":"Other(specify)","drug_cat_2":"Other(specify)","drug_cat_3":"Hycodan"},
    {"drug_name":"Boldenone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Durabolin","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Drostanolone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Equipoise","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Masteron","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Methandrostanolone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Nandrolone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Oxandrolone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Oxymetholone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Parabolan","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Primobolan","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Steroids","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Sustanon","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Testosterone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Trenbolone","drug_cat_1":"Other(specify)","drug_cat_2":"Steroids","drug_cat_3":""},
    {"drug_name":"Midazolam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Ghb","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"GHB","drug_cat_3":""},
    {"drug_name":"Ketamine","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Other sedatives and tranquillizers (specify)","drug_cat_3":"Ketamine"},
    {"drug_name":"Alprazolam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Amytal","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Apodiazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Apolorazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Apotemazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Ativan","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Benzodiazepines","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Bromazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Clonapam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Clonazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Cyclobarbital","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Diazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Etizolam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Fiorinal","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Flubromazolam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Lendormin","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Librax","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Librium","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Lorazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Mandrax","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Methaqualone","drug_cat_3":""},
    {"drug_name":"Nitrazadon","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Nitrazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Novodipam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Oxazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Phenobarbital","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Prazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Seconal","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Temazepam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Trianal ","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing barbiturates","drug_cat_3":""},
    {"drug_name":"Triazolam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Valium","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Xanax","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Clobazam","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Diverted/counterfeit prescription drugs containing benzodiazapines","drug_cat_3":""},
    {"drug_name":"Trazodone","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Other sedatives and tranquillizers (specify)","drug_cat_3":"Trazodone"},
    {"drug_name":"Ambien","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Other sedatives and tranquillizers (specify)","drug_cat_3":"Ambien"},
    {"drug_name":"Zolpidem","drug_cat_1":"Sedatives and tranquilizers","drug_cat_2":"Other sedatives and tranquillizers (specify)","drug_cat_3":"Zolpidem"}
    )
    
RCMP_names = {
    "benzylpiperazine (bzp)": "Benzylpiperazine",
    "3,4-methylenedioxyamphetamine (mda)" : "MDA",
    "amphetamines/salts/derivatives/isomers/analogues" : "Amphetamine",
    "amphetamine" : "Amphetamine",
    "amphetamines" : "Amphetamine",
    "mdma (ecstasy)" : "MDMA",
    "mdma" : "MDMA",
    "methamphetamine" : "Methamphetamine",
    "ephedrine (e)" : "Ephedrine",
    "methylenedioxypyrovalerone (bath salts)" : "MDPV",
    "cannabis resin (hash)" : "Hash",
    "cannabis (marihuana)" : "Cannabis",
    "cannabis" : "Cannabis",
    "cbd cannabidiol" : "CBD cannabidiol",
    "cannabidiol" : "CBD cannabidiol",
    "cannabis resin (hash oil)" : "Hash oil",
    "synthetic cannabinoid" : "Synthetic cannabinoid",
    "cannabidinoid" : "Cannabidinoid",
    "cannabis (marihuana) (plants)" : "Cannabis plant",
    "cannabis resin" : "hash",
    "cocaine" : "Cocaine",
    "lysergic acid diethylamide (lsd)" : "LSD",
    "lsd" : "LSD",
    "dimethyltryptamine (dmt)" : "DMT",
    "phencyclidine (pcp)" : "PCP",
    "psilocybin" : "Psilocybin",
    "mescaline" : "Mescaline",
    "buprenorphine" : "Buprenorphine",
    "carfentanil" : "Carfentanil",
    "codeine" : "Codeine",
    "fentanyl" : "Fentanyl",
    "hydrocodone" : "Hydrocodone",
    "methadone" : "Methadone",
    "oxycodone" : "Oxycodone",
    "heroin" : "Diacetylmorphine",
    "morphine" : "Morphine",
    "opium" : "Opium",
    "mdea" : "MDEA",
    "anabolic steroids and their derivatives" : "Steroids",
    "anabolic steroid" : "Steroids",
    "alprazolam" : "Alprazolam",
    "benzodiazepine" : "Benzodiazepines",
    "lorazepam" : "Lorazepam",
    "4-hydroxybutanoic acid (ghb)" : "Ghb",
    "1,4-butanediol (1-4bdo)" : "Ghb",
    "ghb" : "Ghb",
    "ketamine" : "Ketamine",
    "zolpidem" : "Zolpidem",
    "coca leaves" : "Coca leaves",
    "1-phenyl-2-propanone (p2p)" : "1-Phenyl-2-propanone (P2P)",
    "anthranilic acid" : "Anthranilic acid",
    "benocyclidine (btcp)" : "Benocyclidine (BTCP)",
    "harmaline" : "Harmaline",
    "other" : "Other",
    "phenethylamines" : "Phenethylamines",
    "hydromorphone" : "Hydromorphone",
    "cannabis resin" : "Cannabis resin",
    "cannabis resin oil" : "Cannabis resin oil",
    "shatter (cannabis)" : "Shatter (cannabis)",
    "4-bromo-2,5-dimethoxy - 2.5benzeneethanamine (nexus)" : "4-bromo-2,5-dimethoxy - 2.5benzeneethanamine (Nexus)",
    "lysergic acid (l/a)" : "Lysergic acid (L/A)",
    "ephedra" : "Ephedra",
    "other - prescription drugs" : "Other - prescription drugs",
    "sildenafil citate" : "Sildenafil Citate",
    "tadalafil" : "Tadalafil",
    "barbiturates, their salts and derivatives" : "Barbiturates, their salts and derivatives",
    "gamma-butyrolactone (gbl)" : "Gamma-butyrolactone (GBL)",
    "catha edulis forsk. - preparations/derivatives/alkaloids/salts" : "Catha edulis Forsk. - preparations/derivatives/alkaloids/salts",
    "cathinone" : "Cathinone",
    "other - non-illicit drugs" : "Other - non-illicit drugs",
    "3,4-methylenedioxyphenyl-2-propanone (mdp2p)" : "3,4-Methylenedioxyphenyl-2-propanone (MDP2P)",
    "ethyl ether" : "Ethyl Ether",
    "hydrocloric acid (hcl)" : "Hydrocloric acid (HCL)",
    "piperidine" : "Piperidine",
    "pseudoephedrine (pe)" : "Pseudoephedrine (PE)",
    "white phosphorus (wp)" : "White phosphorus (WP)",
    "phenylpiperidines/intermediates/salts/deriv/analogues" : "Phenylpiperidines/intermediates/salts/deriv/analogues",
    "unknown/unclassified" : "Unknown/Unclassified",
    "other prescription drugs" : "Other prescription drugs",
    "251-nbome" : "251-NBOMe",
    "psychedelic" : "Psychedelic",
    "other - non-illicit drug" : "Other - Non-Illicit Drug",
    "barbiturates" : "Barbiturates",
    "rohypnol" : "Rohypnol",
    "precursor" : "Precursor",
    "opioid" : "Opioid"
    }