location_dict = {
    "armed robbery from hospital / long term care facility":"Theft from hospitals or doctors' offices",
    "armed robbery from dealer/producer (ld,rd,lp)":"Theft from factory or wholesaler",
    "armed robbery from pharmacy":"Theft from pharmacy",
    "break and entry from federal nursing station":"Theft from hospitals or doctors' offices",
    "break and entry from hospital / long term care facility":"Theft from hospitals or doctors' offices",
    "break and entry from licensed dealer":"Theft from factory or wholesaler",
    "break and entry from pharmacy":"Theft from pharmacy",
    "break and entry from physician's office / clinic":"Theft from hospitals or doctors' offices",
    "break and entry from veterinary hospital / clinic":"Theft from hospitals or doctors' offices",
    "breakage from federal nursing station":"Spillage or defect from hospitals or doctors' offices",
    "breakage from pharmacy":"Spillage or defect from pharmacy",
    "forgery from hospital":"Forgery from hospitals or doctors' offices",
    "forgery from veterinary clinic":"Forgery from hospitals or doctors' offices",
    "grab theft from dealer/producer (ld,rd,lp)":"Theft from factory or wholesaler",
    "grab theft from hospital / long term care facility":"Theft from hospitals or doctors' offices",
    "grab theft from licensed dealer":"Theft from factory or wholesaler",
    "grab theft from pharmacy":"Theft from pharmacy",
    "grab theft from physician's office / clinic":"Theft from hospitals or doctors' offices",
    "grab theft from veterinary hospital / clinic":"Theft from hospitals or doctors' offices",
    "impersonation from licensed dealer":"Theft from factory or wholesaler",
    "loss in transit from licensed dealer":"Loss in transit from factory or wholesaler",
    "loss unexplained - after investigation (for lds only) from pharmacy":"Loss Unexplained from pharmacy",
    "loss unexplained from canadian forces":"Loss Unexplained from Canadian Forces",
    "loss unexplained from correctional facility":"Loss Unexplained from Correctional Facility",
    "loss unexplained from dealer/producer (ld,rd,lp)":"Loss Unexplained from factory or wholesaler",
    "loss unexplained from dentist's office":"Loss Unexplained from hospitals or doctors' offices",
    "loss unexplained from emergency medical":"Loss Unexplained from hospitals or doctors' offices",
    "loss unexplained from federal nursing station":"Loss Unexplained from hospitals or doctors' offices",
    "loss unexplained from hospital / long term care facility":"Loss Unexplained from hospitals or doctors' offices",
    "loss unexplained from licensed dealer":"Loss Unexplained from factory or wholesaler",
    "loss unexplained from pharmacy":"Loss Unexplained from pharmacy",
    "loss unexplained from physician's office / clinic":"Loss Unexplained from hospitals or doctors' offices",
    "loss unexplained from precursor institution":"Loss Unexplained from factory or wholesaler",
    "loss unexplained from research facility / laboratory":"Loss Unexplained from research facility",
    "loss unexplained from veterinary hospital / clinic":"Loss Unexplained from hospitals or doctors' offices",
    "manufacturer's defects from hospital / long term care facility":"Spillage or defect from hospitals or doctors' offices",
    "manufacturer's defects from pharmacy":"Manufacturer's Defects from pharmacy",
    "manufacturer's shortages from dealer/producer (ld,rd,lp)":"Shortage from factory or wholesaler",
    "manufacturer's shortages from hospital / long term care facility":"Manufacturer's Shortages from hospitals or doctors' offices",
    "manufacturer's shortages from pharmacy":"Manufacturer's Shortages from pharmacy",
    "manufacturer's shortages from precursor institution":"Manufacturer's Shortages from factory or wholesaler",
    "other (specify) from canadian forces":"Loss Unexplained from Canadian Forces",
    "other (specify) from dealer/producer (ld,rd,lp)":"Loss Unexplained from factory or wholesaler",
    "other (specify) from dentist's office":"Loss Unexplained from hospitals or doctors' offices",
    "other (specify) from hospital / long term care facility":"Loss Unexplained from hospitals or doctors' offices",
    "other (specify) from pharmacy":"Loss Unexplained from pharmacy",
    "other (specify) from precursor institution":"Loss Unexplained from factory or wholesaler",
    "other (specify) from veterinary hospital / clinic":"Loss Unexplained from hospitals or doctors' offices",
    "other from licensed dealer":"Loss Unexplained from factory or wholesaler",
    "overshipment (picking error) from dealer/producer (ld,rd,lp)":"Overshipment (Picking Error) from factory or wholesaler",
    "overshipment (picking error) from pharmacy":"Overshipment (Picking Error) from pharmacy",
    "pilferage from dealer/producer (ld,rd,lp)":"Theft from factory or wholesaler",
    "pilferage from dentist's office":"Theft from hospitals or doctors' offices",
    "pilferage from federal nursing station":"Theft from hospitals or doctors' offices",
    "pilferage from hospital / long term care facility":"Theft from hospitals or doctors' offices",
    "pilferage from licensed dealer":"Theft from factory or wholesaler",
    "pilferage from pharmacy":"Theft from pharmacy",
    "pilferage from physician's office / clinic":"Theft from hospitals or doctors' offices",
    "pilferage from royal canadian mounted police (rcmp)":"Theft from Canadian Forces",
    "pilferage from veterinary hospital / clinic":"Theft from hospitals or doctors' offices",
    "spillage from pharmacy":"Spillage or defect from pharmacy",
    "spillage from canadian forces":"Spillage or defect from Canadian Forces",
    "spillage from hospital / long term care facility":"Spillage or defect from hospitals or doctors' offices",
    "undershipment from hospital / long term care facility":"Undershipment (Picking Error) from hospitals or doctors' offices",
    "undershipment from dealer/producer (ld,rd,lp)":"Undershipment (Picking Error) from factory or wholesaler",
    "undershipment from pharmacy":"Undershipment (Picking Error) from pharmacy"
}

drug_dict = {
    "alfentanil" : "OPIOIDS",
    "alprazolam" : "BENZODIAZEPINES",
    "amphetamine" : "AMPHETAMINE",
    "amphetamine aspartate monohydrate" : "AMPHETAMINE",
    "amphetamine sulfate" : "AMPHETAMINE",
    "barbital" : "BARBITURATES",
    "bromazepam" : "BENZODIAZEPINES",
    "buprenorphine" : "OPIOIDS",
    "buprenorphine (buprenorphine hydrochloride)" : "OPIOIDS",
    "butalbital" : "BARBITURATES",
    "butorphanol (butorphanol tartrate)" : "OPIOIDS",
    "butorphanol tartrate" : "OPIOIDS",
    "cannabidiol (cannabis sativa extract)" : "CANNABIDIOL/DELTA-9-TETRAHYDROCANNABINOL",
    "cannabis" : "CANNABIS",
    "chlordiazepoxide hcl" : "BENZODIAZEPINES",
    "chlordiazepoxide hydrochloride" : "BENZODIAZEPINES",
    "clobazam" : "BENZODIAZEPINES",
    "clonazepam" : "BENZODIAZEPINES",
    "clorazepate dipotassium" : "BENZODIAZEPINES",
    "cocaine" : "COCAINE",
    "cocaine hydrochloride" : "COCAINE",
    "codeine" : "OPIOIDS",
    "codeine (codeine monohydrate ,codeine sulfate trihydrate)" : "OPIOIDS",
    "codeine (codeine phosphate)" : "OPIOIDS",
    "codeine phosphate" : "OPIOIDS",
    "dehydroepiandrosterone" : "STEROIDS",
    "delta-9-tetrahydrocannabinol (cannabis sativa extract)" : "CANNABIDIOL/DELTA-9-TETRAHYDROCANNABINOL",
    "dextroamphetamine" : "AMPHETAMINE",
    "dextroamphetamine saccharate" : "AMPHETAMINE",
    "dextroamphetamine sulfate" : "AMPHETAMINE",
    "dextropropoxyphene napsylate" : "OPIOIDS",
    "diazepam" : "BENZODIAZEPINES",
    "dihydromorphine" : "OPIOIDS",
    "diphenoxylate hydrochloride" : "OPIOIDS",
    "dronabinol" : "CANNABIDIOL/DELTA-9-TETRAHYDROCANNABINOL",
    "ephedrine" : "N/A",
    "ergotamine (ergotamine tartrate)" : "N/A",
    "fentanyl" : "FENTANYL",
    "fentanyl (fentanyl citrate)" : "FENTANYL",
    "flurazepam hydrochloride" : "BENZODIAZEPINES",
    "hydrochloric acid" : "N/A",
    "hydrocodone" : "OPIOIDS",
    "hydrocodone bitartrate" : "OPIOIDS",
    "hydromorphone" : "OPIOIDS",
    "hydromorphone hydrochloride" : "OPIOIDS",
    "ketamine" : "KETAMINE",
    "ketamine (ketamine hydrochloride)" : "KETAMINE",
    "lisdexamfetamine dimesylate" : "AMPHETAMINE",
    "lorazepam" : "BENZODIAZEPINES",
    "meperidine (meperidine hydrochloride)" : "OPIOIDS",
    "meperidine hydrochloride" : "OPIOIDS",
    "meprobamate": "N/A",
    "methadone" : "OPIOIDS",
    "methadone hydrochloride" : "OPIOIDS",
    "methandrostenolone" : "STEROIDS",
    "methylphenidate" : "METHYLPHENIDATE",
    "methylphenidate hydrochloride" : "METHYLPHENIDATE",
    "methylphenidate hcl" : "METHYLPHENIDATE",
    "methyltestosterone" : "STEROIDS",
    "midazolam" : "BENZODIAZEPINES",
    "midazolam (midazolam hydrochloride)" : "BENZODIAZEPINES",
    "morphine" : "OPIOIDS",
    "morphine hydrochloride" : "OPIOIDS",
    "morphine sulfate" : "OPIOIDS",
    "nabilone" : "NABILONE",
    "nalbuphine" : "OPIOIDS",
    "nalbuphine hydrochloride" : "OPIOIDS",
    "nitrazepam" : "BENZODIAZEPINES",
    "normethadone hydrochloride" : "OPIOIDS",
    "opium" : "OPIOIDS",
    "oxazepam" : "BENZODIAZEPINES",
    "oxycodone" : "OPIOIDS",
    "oxycodone hydrochloride" : "OPIOIDS",
    "pentazocine (pentazocine hydrochloride)" : "OPIOIDS",
    "pentobarbital" : "BARBITURATES",
    "pentobarbital sodium" : "BARBITURATES",
    "phenobarbital" : "BARBITURATES",
    "phenobarbital sodium" : "BARBITURATES",
    "phenylpropanolamine hydrochloride" : "AMPHETAMINE",
    "pipradrol hydrochloride" : "N/A",
    "pseudoephedrine" : "AMPHETAMINE",
    "pseudoephedrine hydrochloride" : "AMPHETAMINE",
    "remifentanil (remifentanil hydrochloride)" : "OPIOIDS",
    "somatropin" : "N/A",
    "sufentanil (sufentanil citrate)" : "OPIOIDS",
    "sodium oxybate" : "N/A",
    "tapentadol (tapentadol hydrochloride)" : "OPIOIDS",
    "temazepam" : "BENZODIAZEPINES",
    "testosterone" : "STEROIDS",
    "testosterone cypionate" : "STEROIDS",
    "testosterone enanthate" : "STEROIDS",
    "testosterone propionate" : "STEROIDS",
    "testosterone undecanoate" : "STEROIDS",
    "triazolam" : "BENZODIAZEPINES",
    "zolpidem" : "ZOLPIDEM",
    "zolpidem tartrate" : "ZOLPIDEM",
}